git:
  depth: 1
language: c
os:
  - osx
#  - linux
#  - windows

env:
  global:
    - SDL_VIDEODRIVER=dummy

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang
      - cmake
      - cmake-data

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux"  ]; then sudo apt-get -qq update;    fi

script:
  - echo $TRAVIS_OS_NAME
  - cmake --version
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then clang --version; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo pip3 install -r requirements.txt; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip3 install -r requirements.txt; fi
  - python3 build.py
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bin/darwin64/cetech_develop -compile -src ./examples/develop/src -build ./examples/develop/build -renderer.type noop; fi

